apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 'truenas.inside.prickels.casa'
    path: '/mnt/tank/container-storage/plex'
