apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pv
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: plex-pv
