apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 'freenas.internal.mikeyp.net'
    path: '/mnt/vault/container-storage/plex'
