version: '3.9'
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    volumes:
      - config:/config
    environment:
      - TZ=America/New_York
      - PUID=1003
      - PGID=1007
    restart: always
    network_mode: host

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=freenas.local,rw
      device: ":/mnt/vault/container-storage/homeassistant"