version: '3.7'
services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    environment:
      CADDYPATH: /etc/caddycerts
      ACME_AGREE: 'true'
    volumes:
      - /data/compose/43/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
    network_mode: host
    restart: always

volumes:
  caddy_data:
    external: true
  caddy_config:
