version: '3.7'
services:
  caddy:
    image: mikeyp/caddy:latest
    container_name: caddy
    environment:
      CADDY_CONFIG: |+
        # Plex reverse proxy - not needed but sometimes useful.
        https://plex.mikeyp.net {
          tls mike@mikeyp.net
          proxy / http://plex.internal.mikeyp.net:32400/ {
            transparent
          }
        }
        
        # Reverse proxy to Dream Machine setup - one again not required, but useful if ui.com proxy is slow.
        https://unifi.mikeyp.net {
          tls mike@mikeyp.net
          proxy / https://setup.ui.com/ {
            websocket
            transparent
            insecure_skip_verify
          }
        }
        
        # Homeassistant
        https://home.mikeyp.net {
          tls mike@mikeyp.net
          proxy / http://home-assistant.internal.mikeyp.net:8123/ {
            websocket
            transparent
          }
        }
        
        # Transmission
        https://transmission.mikeyp.net {
          tls mike@mikeyp.net
          proxy / http://docker-01.internal.mikeyp.net:9091/ {
            websocket
            transparent
          }
        }
        
        # Portainer
        https://portainer.mikeyp.net {
          tls mike@mikeyp.net
          proxy / https://docker-01.internal.mikeyp.net:9443/ {
            websocket
            transparent
            insecure_skip_verify
          }
        }
        
        
        
    volumes:
      - caddy_config:/config
      - caddy_data:/data
    network_mode: host
    restart: always

volumes:
  caddy_data:
    external: true
  caddy_config:
