version: '3.7'
services:
  caddy:
    image: abiosoft/caddy
    container_name: caddy
    environment:
      CADDYPATH: /etc/caddycerts
      ACME_AGREE: 'true'
    volumes:
      - caddy_config:/config
      - caddy_data:/data
    network_mode: host
    restart: always
